### ISSUE TITLE
Use in test

### ISSUE THREAD

**Issue by lpil** [lexmag/statix#11]
Hello!

First, thanks for this library :)

I was wondering how you would recommend using this library in test?

I've seen other libraries (such as [this ruby one](https://github.com/Shopify/statsd-instrument#testing)) may provide an in-memory backend that allows one to make assertions about the metrics being recorded. Do you have a similar system? Or is this not something you see value in testing? :)

Cheers,
Louis

**Comment by whatyouhide** [comment]
@lpil we wanted to discuss something like swappable backends for [Fluxter](https://github.com/lexmag/fluxter) (which is very similar to Statix), see https://github.com/lexmag/fluxter/issues/8. At work, we currently don't test stuff by asserting that metrics got reported but maybe there is value in doing that in some cases.

**Comment by jeffrom** [comment]
we like testing some metrics at my job. we made a genserver and have a module that matches the interface of statix, but sends beam messages instead of udp. we found udp a little too flaky for CI.
