### ISSUE TITLE
Support for global tags

### ISSUE THREAD

**Issue by mgartner** [lexmag/statix#13]
Would you accept a PR for a global tags functionality, where you could provided tags that are sent with every metric, and set in configuration:

```elixir
config :statix,
  host: "somehost.com",
  port: 8125,
  prefix: "our_app",
  tags: [Mix.env, "global_tag"]
```

**Comment by mgartner** [comment]
Bump on this. If you can confirm you'd accept this as a PR, myself and some others will work on a PR soon.

**Comment by lexmag** [comment]
Hey @mgartner, sure, PR for adding global tags is welcome. 👍

**Comment by jhwang09** [comment]
A PR is up, could we get a look? This will be an awesome feature to have.

**Comment by lexmag** [comment]
Closing in favor of #19.
