### ISSUE TITLE
Can't get it to work...

### ISSUE THREAD

**Issue by drozzy** [lexmag/statix#32]
Is there any way to know if the UDP packing is being sent?

Because I keep issuing:

```
Myapp.Statix.increment("page_view", 100)
:ok
```

and everything seems to work, but data dog is not showing anything.

**Comment by drozzy** [comment]
FYI I'm running on docker swarm, with an overlay network, and using one agent per host.
Additionally my host is set to "localhost" in statix.

I tested sending to localhost from bash and it works.

**Comment by sb8244** [comment]
Hey @drozzy any luck? Does this work locally when using something like statsd-server debugger?

**Comment by drozzy** [comment]
Sorry, haven't been back to test this.
Please ignore this bug - I'm sure it was something I did wrong.
