### ISSUE TITLE
Connection getting made on compile-time (when `runtime_config: false`)

### ISSUE THREAD

**Issue by dcaixinha** [lexmag/statix#37]
Hey all,

I'm now in the process of migrating some of our apps to use `statix`, and in the process of doing so I've found a really strange behavior. When calling `use` on the module I'm not passing the `runtime_config` option (which defaults to false), as I don't need to change the config at run-time. However, it looks like when using it this way, the connection is made at compile-time instead of run-time. For instance, when booting the application locally, if I don't have the `statsd` container running, my app won't compile with the following error: `== Compilation error in file lib/motus/statix.ex == ** (MatchError) no match of right hand side value: {:error, :nxdomain}`.

I've done some digging and placed some `IO.inspects` around, and it looks like the [Statix.new_conn](https://github.com/lexmag/statix/blob/master/lib/statix.ex#L242) function is really being called at compile-time. However, since that code is inside a `quote` block, it should just return the AST instead of evaluating it, right? :thinking:

Thanks for your help and for the library itself, it's really useful :raised_hands:

**Comment by lexmag** [comment]
Hi @dcaixinha, thanks for bringing up this issue. 💛
During compile-time Statix does not make connections to server, however it does try to get the IP address of the provided `:host` configuration option. That was the error in this case.
I've just pushed a commit (ed353d12352f0ce20c4151fd4b9f52bd9c3a07cb) that should provide much clearer error message.
