### ISSUE TITLE
Should connect accept configuration?

### ISSUE THREAD

**Issue by keathley** [lexmag/statix#39]
We often need to pre-configure statix at runtime before running the `connect/0` function. Would it make sense to allow `connect` to accept a configuration? This would allow us to avoid mutating the application env. I can take a look at this if it's interesting to y'all.

**Comment by mroach** [comment]
We're having to do the same thing as our statsd servers are defined by ENV vars per data centre (a.la Consul). In general it makes sense to support runtime configuration especially for external services. 

Regarding the discussions in #41, this might also be a solid feature to add to a Bleacher Report fork.

**Comment by lexmag** [comment]
#50 should make this possible. Feel free to review the PR. :bowtie:
