### ISSUE TITLE
Configuration evaluated at compile time limitation

### ISSUE THREAD

**Issue by edgurgel** [lexmag/statix#4]
I noticed that the Statsd port and ip configuration is evaluated at compile time only right? Please correct me if I'm wrong.

Would it be possible to change this so it can be defined during runtime? I understand that the `header` needs to be "saved" somewhere so that the `Port.command` will have it to build the full message.

What if we use `Application` env to keep the header there? So as soon as the connection is open we set the header for that connection?

Would that be too hacky? 

I understand that this is a core feature from Statix (the ability to cache the packet header) but it's also very limiting the facet the Statsd host and port needs to be known during compilation :(

**Comment by edgurgel** [comment]
I did this here setting `:conn` as the `Statix.Conn`:

https://github.com/lexmag/statix/compare/master...edgurgel:config-conn?expand=1

Tests are passing 👍 

I don't love the idea of holding "state" through `Application` env but the other options are:

* Have a GenServer to hold an ETS table and query the table (Also maybe `Process.link` so it has a "supervisor")
* Use Process dictionary? It's just for reading and it's a very simple structure to store.

What do you think? :/

**Comment by lexmag** [comment]
Hey @edgurgel, thanks for opening an issue.
Yes, configuration is evaluated at compile and won't work perfectly for everyone.

I like options you've suggested, what if we evolve them to:

1. have the changes you've done to use `Application` env (maybe ETS like you've suggested), plus use Process dictionary to store the header value retrieved from app env (thus we effectively cache it).
2. make a simple pool of processes, like it is done in https://github.com/lexmag/fluxter

We can even implement both and compare throughput.

What are your thoughts on it?

**Comment by svetob** [comment]
@lexmag Just got bitten by this bug. We can do a temporary workaround by recompiling the app just before launching it, but i'm wondering if you have an ETA on merging this fix?

**Comment by lexmag** [comment]
Hey @svetob, I will look into fixing this later during the week. Feel free to send a PR if you want to give this a try, that would be great. :)

**Comment by svetob** [comment]
Thanks so much!

Don't think I have time for a PR right now though unfortunely :(

**Comment by lexmag** [comment]
Sorry, it took some time to load test this feature.
This issue should be solved in 731162bad8427175c5d075eea9f145d98b5b4b07, and available in the next version which I will release on Monday. :bowtie:

**Comment by edgurgel** [comment]
This is awesome!
