### ISSUE TITLE
Tags format not supported by InfluxDB

### ISSUE THREAD

**Issue by sahilpaudel-pe** [lexmag/statix#52]
I am using influxdb and telegraf metrics for statsD 
but I couldn't find the tags I am sending using statix, I am using Grafana to visualize the data.

Then I did little digging and found that 
InfluxDB understands tags sent in this format 

> <tag_key>=<tag_value>,<tag_key>=<tag_value>

I changed the format according and used following syntax.
```status_count = "#{prefix}.#{conn.status}.count"
tag1 = "method=#{conn.method}"
tag2 = "handler=#{controller}_#{action}"
tag3 = "service=carbon"
tag4 = "env=#{Mix.env()}"
MyApp.Statix.increment(status_count, 1, tags: [tag1, tag2, tag3, tag4])
```

I am able to see the status_count measurement but tags are not available there in the grafana.

**Comment by sahilpaudel-pe** [comment]
Incorrectly filed.

**Comment by lexmag** [comment]
@sahilpaudel-pe thanks for the report, I'll investigate it.
I can also recommend checking https://github.com/lexmag/fluxter for native InfluxDB support.

**Comment by sahilpaudel-pe** [comment]
@lexmag Thanks for getting back.
The thing is all other data is received by influxDB except for tags which is the concern for me right now. I am stuck in tags, if you can figure that out it world be great.
As for rest stuff statix is doing great.
